App:
  targets:
    - name: "ASMR"
#      disable: true
      type: "MusicAlbum"
      async: true
      subItems:
        sortBy: "IndexNumber,Name"
        fields: "ItemCounts,PrimaryImageAspectRatio,CanDelete,MediaSourceCount"
    - name: "Adult"
      type: "Movie"
      async: false
      jitter: 5
      disable: true

JellyfinConfig:
  host: http://m73:8096
  apiKey: "5f77f3f3b5994d0ba1596168622f7563"
  userId: "8e7118d28d104dd6acdad76c7ac58647"
  debug: false

ScraperConfig:
  query:
    startIndex: 0
    limit: 3000

Clients:
  AsmrOneConfig:
    targetName: "ASMR"
    host: https://api.asmr-200.com
    parsePathRegex: "(RJ|VJ|BJ)\\d+"
    forceMissingInfo: true
    forceMissingImage: false
    debug: false
  JavDBConfig:
    targetName: "Adult"
    host: "https://javdb.com"
    parsePathRegex: "[a-z|A-Z|FC2]+-\\d+[a-z|A-Z]?"
    lang: "zh"
    forceMissingInfo: false
    forceMissingImage: false
    debug: false

EnableProgressBar: false